### ISSUE TITLE
Open link keystroke fails to activate on nonexistent links due to when expression

### ISSUE THREAD

**Issue by darbaga** [svsool/vscode-memo#127]
The open link command, if invoked by a keystroke on a link that does not yet have a corresponding file, fails to execute due to the refUnderCursorExists constraint. If the command is ran manually (through the command pallet) it runs fine.

I'm not very experienced with the vscode extension API, but my suspicion is is it fails because getRefUriUnderCursor only looks through existing files for references. The actual file creation happens in openDocumentByReference.

I'd be willing to do a PR, but I don't really know what needs changing. If you want a PR, give me some pointers on how this needs to be fixed and I'll try.

**Comment by svsool** [comment]
Thanks for reporting! 

It was fixed in #130 by @bs (thanks for contribution ❤️) and will be released today.
