### ISSUE TITLE
`Extract note` command should insert the link in the file that it's extracting from, automatically

### ISSUE THREAD

**Issue by abuggin** [svsool/vscode-memo#135]
Verbose title, but basically what it says.

Right now, when you extract a note, you choose a file name and it opens that file with the content extracted.
What I find myself doing is that every time I extract a note, I go back to the place of extraction and add a link (sometimes even a ![[link]] )

Ideally I'd love to have that step be automatically done.

**Comment by svsool** [comment]
That's a good idea. I think I had something like on my list as well and even started working on it, but did not manage to finish 😅. Also, this issue is perhaps for https://github.com/svsool/vscode-markdown-kit?

**Comment by abuggin** [comment]
Moving to other repo
