### ISSUE TITLE
Piped wikilinks don't work well in table cells

### ISSUE THREAD

**Issue by zcysxy** [svsool/vscode-memo#164]
When I have a piped wikilink in a table cell, I have to type `\|` to avoid it is parsed as table syntax. And then all work well in the preview, the link is clickable and leads to the right file. However, when I hover on the link in editor, it says the file is not created yet. And it will create a `.md` file after I Ctrl + click on it.

![image](https://user-images.githubusercontent.com/48207708/96753907-213c7600-1403-11eb-8217-3de2a4df0fc8.png)

![image](https://user-images.githubusercontent.com/48207708/96753934-2a2d4780-1403-11eb-87bb-808dca640d01.png)

**Comment by svsool** [comment]
Thanks for reporting. It was fixed and will be released in the next version.
