### ISSUE TITLE
Feature Request - Ability to disable IntelliSense and/or other features

### ISSUE THREAD

**Issue by account-sxf** [svsool/vscode-memo#167]
I use a few other plugins to aid my codium-powered Zettelkasten in addition to vscode-memo. Consequently, I'd like to disable the intillesense feature while leaving other features intact. The available options in the extension UI are quite minimal and don't allow much customization. If you want to implement that feature it'll let people mix and match more plugins with vscode-memo.

**Comment by svsool** [comment]
Most of the features can be disabled now. Will be released in the next version of Memo.

![image](https://user-images.githubusercontent.com/1452141/97780201-d271a780-1b8b-11eb-8235-acacf418b764.png)

**Comment by account-sxf** [comment]
@svsool wondeful! I'll pick up the update 👍
