### ISSUE TITLE
Feature Request: [[wiki links without file extension]]

### ISSUE THREAD

**Issue by cedardocster** [svsool/vscode-memo#194]
All my note files are ".md" files and the internal links to other notes are like [[this note]] to refer to a file named "this note.md".

Would it be possible to allow for a default file extension so they can be excluded from the link text?

Thanks,
- Dave

**Comment by svsool** [comment]
Hello Dave, I'm not sure I understand, could you please clarify?

**Comment by cedardocster** [comment]
In most personal wiki applications I've seen, the wiki links are all [[like this]] and its assumed that the extension is either ".txt" or ".md", so when the program is presented with [[this link]], when you click on it, it opens "this link.md".

From what I can tell with your extension you require to include the file extension inside the brackets.

Would it be possible to set a default extension like ".md" so this would work with just the wiki file titles without the extension?

**Comment by svsool** [comment]
Memo does not require extension as part of the link for `.md` files.

The following example is with the Memo's [help](https://github.com/svsool/vscode-memo/tree/master/help) folder opened in VS Code.

![image](https://user-images.githubusercontent.com/1452141/99124759-6c653580-260b-11eb-9851-1b1d0f944d40.png)

It can be seen that files in the file tree are with `.md` extension, but according links in the editor are not.

**Comment by cedardocster** [comment]
Oh I see, thank you. Sorry to take up your time on this then - I should
have just installed it and tried it (but I'd been trying a bunch of things
and had started just going by the presented info and hadn't found that)

This looks like just what I've been looking for - thanks for making it!!

- Dave
