### ISSUE TITLE
Feature request: follow link under cursor

### ISSUE THREAD

**Issue by harveyr** [svsool/vscode-memo#2]
Like in Obsidian, it would be great if something like `cmd-enter` would open the link under your cursor. Even better than Obsidian: it would be great if this worked not only for links to `[[other notes]]` but also `https://external-links`. 

Thanks!

**Comment by svsool** [comment]
Hello, @harveyr!

About `cmd-enter`, it should actually work out of the box in VSCode if you bind command called "Open link" to `cmd-enter`.

That's how I have it in my `keybindings.json` 

![image](https://user-images.githubusercontent.com/1452141/86812917-3d045200-c088-11ea-949e-0fe4a2b79414.png)

About opening `https://external-links`, thanks for the idea I will add it on my list.

**Comment by harveyr** [comment]
Thank you!

**Comment by harveyr** [comment]
Followup: the _Open Link_ command appears to work both for internal links and web URLs, so there's nothing for you to add to your list. :)

**Comment by RoneoOrg** [comment]
In plain text, easier to copy and paste:

```
    // Follow Markdown link (requires Markdown Memo)
    {
      "key": "ctrl+enter",
      "command": "editor.action.openLink"
    }
```

You can open `keybindings.json` with `Ctrl+Shift+P` → `Open Keyboard Shortcuts (JSON)`

**Comment by memeplex** [comment]
I would like to revisit this issue. I see two things undesirable about the proposed solution:
1. It's not active by default even though following links is so important to Memo. Moreover, there is an asymmetry in that C-S-Enter works OOTB. This amounts to a confusing initial experience.
2. C-Enter conflicts with such a basic vscode editing command as Insert Line Below.

I propose to provide C-M-Enter (Ctrl-Alt-Enter or Cmd-Opt-Enter) as a default shortcut. AFAICS it's not taken by vscode.

**Comment by revett** [comment]
I use the following to avoid it clashing with other `cmd+enter` shortcuts:

```json
{
  "key": "cmd+enter",
  "command": "editor.action.openLink",
  "when": "editorTextFocus && resourceExtname == .md"
 }
```

Taken from: https://stackoverflow.com/questions/69261812/is-there-a-way-to-enable-keyboard-shortcuts-only-when-specific-file-types-are-op
