### ISSUE TITLE
no extension found in marketplace (linux)

### ISSUE THREAD

**Issue by digitalsignalperson** [svsool/vscode-memo#202]
I tried searching for 
- Markdown memo
- svsool.markdown-memo
- Ctrl+P + ext install svsool.markdown-memo

and I get "No extensions found."

Code OSS 1.51.1
Electron 9.3.4
Arch Linux x64 5.4.77-1-lts

versus on a windows computer it does find the extension

**Comment by tamuratak** [comment]
See https://github.com/microsoft/vscode/issues/107997#issuecomment-703245178

**Comment by digitalsignalperson** [comment]
thanks. Ah so this extension is not on open vsx registry. No problem, can work around
