### ISSUE TITLE
Issues on markdown preview rendering

### ISSUE THREAD

**Issue by grainfire** [svsool/vscode-memo#21]
Thanks for the great work! Exactly what I was looking for. 

I have a few questions on how you set up your markdown preview. Right now the images/note embed and link label doesn't work for me:

![image](https://user-images.githubusercontent.com/1624300/87835132-1e007f80-c841-11ea-9abd-776a6bd62d30.png)

As you can see the label and embed don't show up. I am using the latest 0.1.8 version.

**Comment by svsool** [comment]
Hi,

Do links work in the text editor? I suspect that use some other plugin for markdown preview other than VSCode built-in markdown preview which Memo extends. Can it be the case?

**Comment by grainfire** [comment]
You are right! After disabling markdown related extension one by one, it turns out "Markdown extended" is the one that causes the preview problem. Thanks
