### ISSUE TITLE
suggestions for publishing notes as static website

### ISSUE THREAD

**Issue by epogrebnyak** [svsool/vscode-memo#210]
I understand Memo is an excellent plugin to manage notes on a local computerin VS Code, many thanks for supporting open source counter-part for Roam and Obsidian. I was wondering is there is a suggested workflow to render Memo notes as a static html site. Would by-directional links need some specail handling or there is already a solution to convert them to HTML?

**Comment by srid** [comment]
You can publish using https://neuron.zettel.page/

Make sure to enable subdir if you are using them: https://neuron.zettel.page/subdir.html

There is a docker image to get started

**Comment by epogrebnyak** [comment]
Thank you, @srid!
