### ISSUE TITLE
Feature Request: Option to Default Backlinks to Collapsed

### ISSUE THREAD

**Issue by lachyc** [svsool/vscode-memo#22]
The backlinks pane can be hard to quickly navigate when all entries are uncollapsed. Collapsing the view makes it far more easy to read at a glance (in my opinion). A setting to control the default behaviour would cater to a users preference.

![Screen Shot 2020-07-18 at 14 18 40](https://user-images.githubusercontent.com/18381424/87844575-a6465980-c901-11ea-9d39-48ed6dfccc2a.png)
![Screen Shot 2020-07-18 at 14 17 33](https://user-images.githubusercontent.com/18381424/87844576-a9d9e080-c901-11ea-8c18-364bf7d5bdfe.png)

**Comment by svsool** [comment]
Hi,

Thanks for the suggestion. 

It should be possible to implement:

1. New `enum` config property can be added to package.json `backlinksPanelFilesCollapsedState` = `collapsed | expanded`
1. That property should be passed then to `Backlink` constructor as a parameter [here](https://github.com/svsool/vscode-memo/blob/606cead0dbe1b7e4480f470d449dc6a7a5add8c9/src/extensions/BacklinksTreeDataProvider.ts#L68)
1. Profit

I would be happy if someone from Memo's community will try out to implement it. It should be pretty easy to [contribute](https://github.com/svsool/vscode-memo/blob/master/CONTRIBUTING.md) to the codebase.

**Comment by svsool** [comment]
Hi,

It will be release in the next version.
