### ISSUE TITLE
Feature request: allow formatting of included files to remove border and heading.

### ISSUE THREAD

**Issue by muteboy** [svsool/vscode-memo#226]
Feature request:
When using the ![[file]] syntax as follows:
```
# Daily note for 2020-12-14

here is yesterdays: ![[2020-12-13]]

End of note
```
the included file is displayed with a border like this:
![image](https://user-images.githubusercontent.com/10484438/102070114-1e18a180-3e18-11eb-8c38-8a2d5b2e49a1.png)

It would be nice to be able to format the included file without the border, and with the title removed, so that it looks like just another part of the document. That would allow the creation of large documents from multiple smaller pieces.

**Comment by svsool** [comment]
Hi @muteboy, you could try [using your own css styles](https://code.visualstudio.com/docs/languages/markdown#_using-your-own-css) to achieve an individual look.

**Comment by svsool** [comment]
Feel free to reopen this issue if something.

**Comment by muteboy** [comment]
That makes sense! I'll figure it out. Thank you

**Comment by hellquist** [comment]
Hi! Thanks for a great tool.

The "using-your-own-css-styles" thing seems to work, I managed to remove the border, margin and padding via the selectors you suggested.

However, is there a list of CSS selectors for the embedded files somewhere? From the markdown preview I cannot "inspect" or "view source". I am currently trying to find a way to remove the title of the embedded note, but so far no luck, and it is tricky to guess the name of a selector. If you have any tips & tricks on how to see the generated preview code I'm all ears. :)

**Comment by hellquist** [comment]
Found it! In case someone else is looking:

You can inspect everything VSCode does with the in-built DevTools. CMD|Ctrl+Shift+I or select from the help menu.
