### ISSUE TITLE
Feature request: templates, at least for daily notes

### ISSUE THREAD

**Issue by muteboy** [svsool/vscode-memo#227]
I like the daily note feature. It would be great to be able to specify a template for it, with some headings, and even an included file. like a todo list.

For example:
```
# Daily note for {date}

This is a #dailynote or #journal

# Existing todo list

![[todo]]

# other heading

etc
```

This templating could be used elsewhere as well, wherever multiple notes with the same structure are required.

**Comment by svsool** [comment]
Hi, if I understood it right [Auto Snippet](https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.auto-snippet) extension could do what you want. See [this comment](https://github.com/svsool/vscode-memo/issues/107#issuecomment-691515964) for reference.

**Comment by muteboy** [comment]
That does the trick! Thank you.
