### ISSUE TITLE
Features Approval: new-note template, new-note command

### ISSUE THREAD

**Issue by madacol** [svsool/vscode-memo#24]
I'm willing to implement following features:

1. **New note template**
The template could be set in a configuration (string) or an optional file, *whichever you prefer*
And embedding data with `{title}` and maybe `{date}`. *For my use-case I don't really need **date**, but I presume it will be a popular feature*

2. **New note command**
Asks for *filename/title* and pass it as the `reference` parameter to `openDocumentByReference()`

Basically what this extension does https://github.com/monferrand/mzettel but integrated so the template works when **cmd/ctrl+clicking** a new wiki-link

![new command and template](https://raw.githubusercontent.com/monferrand/mzettel/master/docs/note_creation.gif)

---

If you agree to implement those features, then I need your feedback:

1. Would you like the template to be set in a configuration or a file? or any other idea?
2. Do you agree with the `{title}` syntax?
3. Would you like an empty template as default or `# {title}` or any other?

**Comment by lachyc** [comment]
Would you support multiple templates with some sort of option to choose which template on new note creation and support a default new note template? If so I think the template as a file would be the most user-friendly approach. Otherwise a string makes sense as it would be more or less a default note header.

**Comment by madacol** [comment]
I didn't intend to support multiple templates.

I could give it a try if @svsool agrees to it, but I'm not sure how the interface would be, maybe a folder like `.templates` an put all the templates in there?

Nevertheless, I cannot promise to do it, I barely got confidence to do this because I intend to guide (copy :laughing:) from the extension mentioned

**Comment by svsool** [comment]
Hi @madacol,

Thank you for spending the time and figuring out how to implement these features!

My 0.02$:

1. **New note template**

If we want to implement this feature, I would like to understand if we can potentially surpass the functionality of [VSCode snippets](https://code.visualstudio.com/docs/editor/userdefinedsnippets) or at least come close. I can see that variables for inserting the current date and time already supported by snippets.

I suggest trying out snippets first and see if it covers our needs. If yes we can add it later to the help documentation to spread best practices with the rest of the users.

I would be interested to hear your opinion about this 🔼 suggestion.

2. **New note command**

It would be nice to have this feature implemented. 

More ideas from me:

- Configuring default folder where new notes are created on entering short reference
  - Notice: Memo works both with short references and long (absolute) references on filename collision `[[My note]]` vs `[[Root folder/My note]]`
- Inferring folder dynamically based on the currently opened document

Do you have some other ideas?

**Comment by abuggin** [comment]
Regarding the `note template` and the VSCode snippets:
[Extensions (like Memo in this case) can supply their own snippets](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_install-snippets-from-the-marketplace)
We could supply some basic functionality based on this extension use case:

- journal 
- books
- resources?
- ???

**Comment by madacol** [comment]
Regarding the template

Thanks @svsool! :tada:
**VSCode snippets** along with the extension **Auto Snippet** completely solve my use case.
**VSCode snippets** alone should solve @lachyc use case too

@abuggin I think its a good idea to have basic templates :+1:, but I believe they should be part of the documentation, not the extension itself. I think not many templates are usable right away without some customization, just a different language alone would make most template unusable.

**Comment by madacol** [comment]
Regarding the **New note command**

VSCode's built-in command `New file` already creates a file like your second *use case*:

> Inferring folder dynamically based on the currently opened document

Which satisfy my use case too, because **Auto Snippet** triggers the template on file creation

---

How should the *new note command* work for your use case?. This is how I infer the logic:

Check if there's a configured default folder (is a non-empty string?)
- **if yes:** Ask for `reference`, **if it's short:** create note in configured folder, **if long:** create it relative to root folder?
- **if no:** call `New file` command

Correct me if I got anything wrong

**Comment by svsool** [comment]
> Regarding the **New note command**
> 
> VSCode's built-in command `New file` already creates a file like your second _use case_:
> 
> > Inferring folder dynamically based on the currently opened document
> 
> Which satisfy my use case too, because **Auto Snippet** triggers the template on file creation

Given said it would be good to ask:

Do you still have a need in "new note" command?

> How should the _new note command_ work for your use case?.

Those were just an initial ideas / suggestions. In my case new file command is fine.

Regarding default folder + focused document folder logic - I gave it one more thought and I think it's not flexible enough and quickpick popup with long reference autosuggest (like any terminal does for paths) will do that job much better.

@madacol

**Comment by madacol** [comment]
> Do you still have a need in "new note" command?

Not really. In that case I'll just dismiss this issue, just wanted to help if needed.

Anyway, thanks a lot for the suggestions (very helpful beyond this issue) and thanks for this awesome extension 👍
