### ISSUE TITLE
Support custom locations when creating daily notes

### ISSUE THREAD

**Issue by alex-rozenshteyn-leapyear** [svsool/vscode-memo#247]
I'd like to have my daily notes in the format `Daily Notes/%YYYY/%MM/%YYYY-%MM-%DD.md`. Memo has no trouble finding them when they're in this location, but it creates them at top level.

**Comment by svsool** [comment]
Hi, it seems like a special case of https://github.com/svsool/vscode-memo/issues/38 where I explained a more robust solution to this problem, which can also be a bit revised to support your use case.

I think it makes sense to close this one in favor of https://github.com/svsool/vscode-memo/issues/38.
