### ISSUE TITLE
Support for TextBundle

### ISSUE THREAD

**Issue by ryanjm** [svsool/vscode-memo#249]
Have you considered supporting [TextBundle](http://textbundle.org/) for handling images?

**Comment by svsool** [comment]
Hi Ryan, thank you for asking! 

From a design standpoint, this extension does not aim to introduce support for the other file formats like this and support only most common file formats that VS Code or Marketplace extensions do support. 

As of today, it seems like VS Code is not on the list of supporting apps yet.
