### ISSUE TITLE
Graph view for knowledge base

### ISSUE THREAD

**Issue by sntxerror** [svsool/vscode-memo#272]
Finally, someone should have been request it :)

It might be implemented with a whole knowledge base view, and maybe with single note/folder view options.

If there will be a way to implement basic functions as "Add", "Delete", "Rename" right in a graph view that would be awesome, but it seems much more complicated.

**Comment by michael-guimet** [comment]
Hi. You might want to try md-graph: https://marketplace.visualstudio.com/items?itemName=ianjsikes.md-graph

It works very well with memo.

**Comment by harveyr** [comment]
There's also Markdown Links, which is what Foam uses: https://marketplace.visualstudio.com/items?itemName=tchayen.markdown-links

I only tried it once very briefly, but it seemed to work.

**Comment by faydanube** [comment]
> There's also Markdown Links, which is what Foam uses: https://marketplace.visualstudio.com/items?itemName=tchayen.markdown-links
> 
> I only tried it once very briefly, but it seemed to work.

I didn't find a way to set []() to [[wiki-links]]? Do you know how to do that?

**Comment by faydanube** [comment]
> Hi. You might want to try md-graph: https://marketplace.visualstudio.com/items?itemName=ianjsikes.md-graph
> 
> It works very well with memo.

it works very well! 
thanks a lot!

**Comment by faydanube** [comment]
> Hi. You might want to try md-graph: https://marketplace.visualstudio.com/items?itemName=ianjsikes.md-graph
> 
> It works very well with memo.

I used it for a while, then gave up on ...... mainly because of the multi-folder problem

**Comment by svsool** [comment]
Hi,

I'd prefer it implemented as a separate vscode extension similar to those that were shared in this issue.

**Comment by srid** [comment]
> I used it for a while, then gave up on ...... mainly because of the multi-folder problem

Information standardization is one solution. Can multiple app authors agree on particular spec? For example, in regards to linking syntax this would look like: https://github.com/tchayen/markdown-links/issues/28
