### ISSUE TITLE
Auto-creation in the preview does not match the rules in the source file

### ISSUE THREAD

**Issue by faydanube** [svsool/vscode-memo#285]
![auto_create](https://user-images.githubusercontent.com/8817046/109391791-e4096700-7953-11eb-995e-2a0ae26a13d7.gif)

**Comment by svsool** [comment]
Hi, it's hard to infer what you are trying to achieve in this screencast. Please provide a list of steps to reproduce the problem.

**Comment by faydanube** [comment]
> Hi, it's hard to infer what you are trying to achieve in this screencast. Please provide a list of steps to reproduce the problem.

`pages/a.md`
```md
## [[a a a]]
```

1 In markdown privews: ctrl + mouse click, A file named 'a_a_a.md' will be created in `pages/`
2 In plain markdown text: ctrl + mouse click, A file named 'a a a.md' will be created in `/`

The first is the ideal result

**Comment by svsool** [comment]
>  In markdown privews: ctrl + mouse click, A file named 'a_a_a.md' will be created in pages/

Files can't be created in preview mode by clicking on the link given how vscode native markdown preview is currently implemented (tooltip mentions it). See [this issue](https://github.com/microsoft/vscode/issues/102532) for reference. 

![image](https://user-images.githubusercontent.com/1452141/109396466-684ef080-793a-11eb-845f-4111960918de.png)

Do you use some other extension for markdown preview? Memo works only with native preview.

**Comment by faydanube** [comment]
thanks very much.
