### ISSUE TITLE
CPU usage on file rename

### ISSUE THREAD

**Issue by harveyr** [svsool/vscode-memo#286]
Hello!

The link-update process after a file rename is very CPU intensive. On my laptop, all 8 cores are ~100% consumed for 10 or 15 seconds. I have a little under 1700 files in my knowledge base, amounting to about 44,000 lines.

I won't pretend to know what the ideal solution is. As a workaround, I wrote a rename script that uses ripgrep to find all files that have references to the renamed file. This works more or less instantaneously. Here's the current state of that script, in case it's helpful: https://gist.github.com/harveyr/bac46beecd711ce374fa2829a0f4716b

Perhaps Memo could use more efficient search tools if they're available on the system? I'm actually pretty happy with my workaround, so I won't be offended if this isn't a priority.

Otherwise, I'm quite happy with Memo and I really appreciate your work on it! :clap:

**Comment by svsool** [comment]
Hi, @harveyr!

That's right, linear sequential scanning isn't that fast. Rigrep could be used to speed it up. Another approach is to use indexing with workers or LSP, but it would require a good part of Memo re-architectured. So far, it served me well without indexing complexity in place, so probably using something like rigrep would be more preferable.

I might take a look at some point but open to contributions as well.

**Comment by svsool** [comment]
Hi 👋 , [ripgrep](https://github.com/BurntSushi/ripgrep) (shipped with [vscode binary](https://github.com/microsoft/vscode-ripgrep)) should be used in the latest version of Memo. Please update from Marketplace!

The difference on 2k files test workspace (1 file with ref to rename, the rest are mock files with some content and other refs) is roughly the following:

- Before (it takes ~10 seconds on 2k files test workspace for rename pop-up to appear)

![Rename on a big workspace before](https://user-images.githubusercontent.com/1452141/148644691-53e82f71-e6b4-4f72-9253-fc96625fc840.gif)

- After (rename pop-up appears more or less instantly)

![Rename on a big workspace after](https://user-images.githubusercontent.com/1452141/148644703-f5bba06c-9d03-4dd8-a4b5-a9e0ea04635e.gif)

The more files containing the ref the slower renaming process will be, but files not containing the ref should be now filtered away by rigrep and rigrep performance seems much better for that size of workspace.

**Comment by jowitte** [comment]
Awesome, thanks! Kudos...
