### ISSUE TITLE
Backlinks panel does not show context

### ISSUE THREAD

**Issue by madacol** [svsool/vscode-memo#29]
This is the sample image in the **README.md** about backlinks

![backlinks](https://raw.githubusercontent.com/svsool/vscode-memo/master/help/Attachments/Backlinks%20panel.png)

I think I see some context surrounding the reference.

Is that supported and it's now broken? or that was never implemented?

**Comment by svsool** [comment]
Hi,

It works as designed. You can open [help](https://github.com/svsool/vscode-memo/tree/master/help) folder in VSCode and backlinks panel for [this](https://github.com/svsool/vscode-memo/blob/master/help/Daily/2020-07-05.md) file, it should look the same as in the screenshot.

I agree that backlinks logic is not ideal right now. I think better logic would be to use outline aka breadcrumbs for every link, for instance imagine you have the following structure:

```
# Books

- [[Book Genre 1]]
  - Book Name 1
    - [[Read Next]]
```

It would be nice if description of `[[Read Next]]` link in backlinks panel would contain `Books > [[Book Genre 1]] > Book Name 1` information providing more context about ascendent / descendent hierarchy where link is used.

Another dumber way to show surrounding context is to configure amount of lines that should be shown before / after then link similar to how `grep -C num` works.

I think providing descent backlinks context is an interesting and challenging problem to solve.

I'm interested in hearing more ideas and use cases.

**Comment by madacol** [comment]
Ahhh, I understand now, it only shows the context that's *after* the reference. All my examples only have context *before* it, that's why they're always empty.

---

I don't have any strong opinions about how backlinks should work. I'm new to this note-taking system and I'm using it for a specific project. I'm still figuring this out
