### ISSUE TITLE
Use "Go to Definition' to open links?

### ISSUE THREAD

**Issue by sudoandros** [svsool/vscode-memo#297]
Hi. First of all, awesome extension!

I've been wondering if there is any reason why not to use "Go to definition" to open links? Looks very intuitive to me. Strange that you're in fact mentioning "Peek and Go to Definition for links" in the #9. And indeed, I can see all references to the same link but there is no "Go to Definition" option. Am I missing something in the extension or did I misunderstand your previous comment?

**Comment by svsool** [comment]
Hi, "Go to definition" equivalent is called "Open link" which also handles the creation of new notes on the fly if it does not exist, unlike "Go to definition," which usually does do anything like that, it's not available via context menu though as you noticed, but can used with shortcut or via "cmd/ctrl + click".

![image](https://user-images.githubusercontent.com/1452141/110949317-23b85180-834b-11eb-8abf-d558dd2eca62.png)

**Comment by sudoandros** [comment]
Yeah, I know about "Open Link" action. It's just not very convenient to use a separate action with its own shortcut while there is very suitable (at the first glance) "Go to Definition". I hadn't thought of this action acquiring a side effect in such case. Maybe it isn't a good idea after all. Well, I guess I'm gonna make a shortcut for link opening :) Thanks for response
