### ISSUE TITLE
feature request: markdown file embedding

### ISSUE THREAD

**Issue by alexisargyris** [svsool/vscode-memo#3]
I understand that for the time being Memo can only embed image files. Being able to embed one markdown file into another would be very useful in order to introduce structure to a set of notes. Do you think that such a feature may be included in the roadmap?

**Comment by svsool** [comment]
Hello,

I had this in mind and it sounds like a good feature to have. I tried to come up with something and here is what I got so far:

Embedding files.md
![image](https://user-images.githubusercontent.com/1452141/86838527-f410c580-c0a8-11ea-904f-483d747d46a3.png)

Features embedded.md
![image](https://user-images.githubusercontent.com/1452141/86838546-fc690080-c0a8-11ea-9eca-ae482e457eb8.png)

Preview of Embedding files.md

![image](https://user-images.githubusercontent.com/1452141/86839045-97fa7100-c0a9-11ea-8d7c-6fa91dfe99a4.png)

What do you think?

Still need to figure out what to do with cyclic links 🙂 .

**Comment by alexisargyris** [comment]
This is perfect as far as I'm concerned. A way to adjust how the embedded file is displayed (e.g. via CSS like Obsidian does?) may also prove useful. As far as cyclic links are concerned maybe you could use something like a counter to check how many levels of embedding have happened and stop the process after a reasonable number of times? Thanks!

**Comment by svsool** [comment]
> A way to adjust how the embedded file is displayed (e.g. via CSS like Obsidian does?) may also prove useful.

You can do it already in VSCode out of the box. I haven't tried myself though.

https://code.visualstudio.com/docs/languages/markdown

![image](https://user-images.githubusercontent.com/1452141/86940889-fd06a300-c14b-11ea-9281-2f6948b935d7.png)

I figured the solution for cyclic links. 

Now I think if preview on hover should support embedded markdown or not, basically VSCode does not provide anything other than markdown support in hover popups and I guess embedding markdown into markdown might be looking not that cool as it looks with html.

**Comment by alexisargyris** [comment]
ok, I installed v0.1.6 and I see this:

![embedding](https://user-images.githubusercontent.com/1640855/87013179-ebb4a980-c1d2-11ea-9550-b35951e8cee4.png)

What am I missing?

**Comment by svsool** [comment]
hey, v0.1.6 does not include that feature yet, only this https://github.com/svsool/vscode-memo/issues/4

**Comment by alexisargyris** [comment]
ok, I'll wait for that to be released in order to have a look at the css. Thanks

**Comment by svsool** [comment]
Hello!

You can test out markdown embedding feature in v0.1.8 along with [other improvements](https://github.com/svsool/vscode-memo/blob/master/CHANGELOG.md). 

Remember to reload VSCode window on updating from marketplace.

**Comment by alexisargyris** [comment]
works great!
