### ISSUE TITLE
preview latex

### ISSUE THREAD

**Issue by wnrpaul** [svsool/vscode-memo#305]
Hello, the preview on hover doesn't seem to work with latex equation.

![Screenshot 2021-03-18 at 23 20 36](https://user-images.githubusercontent.com/80902403/111705147-8d02fd80-8840-11eb-8f3e-551b337fbfee.png)

Regards,

**Comment by svsool** [comment]
Hi,

Natively vscode hover popup supports either markdown string (subset of it without latex support, see [this comment](https://github.com/microsoft/vscode/issues/32205#issuecomment-321415346)) or plaintext, so not much can be done at this point about it.

Here is the issue about html support in hover popup https://github.com/microsoft/vscode/issues/40607.

**Comment by jsamr** [comment]
@svsool According to the link you shared, `supportHtml` property on  `MarkdownString` has been released to insider preview on october 13th! I believe this feature is now feasible.
