### ISSUE TITLE
Any Clues on How to render [[]] in MDX / Remark

### ISSUE THREAD

**Issue by phil-lgr** [svsool/vscode-memo#309]
Hi there, 

I'm so glad to have found your project, thanks for creating it.

Would you have any clues on how to tell mdx to resolve the links created with Memo [[]] so that we can render actual pages into a docs website ?

**Comment by phil-lgr** [comment]
this is close https://github.com/landakram/remark-wiki-link

**Comment by phil-lgr** [comment]
is there any reason why you went with `[[Real Page|Page Alias]]` instead of `[[Real Page:Page Alias]]` ? the latter seems to be more in use? I'm thinking out loud

**Comment by phil-lgr** [comment]
![image](https://user-images.githubusercontent.com/9644867/112024271-68da4180-8b0a-11eb-90db-3b5f665a8d7d.png)

prettier does not work well with the | character in table whereas : works fine

![image](https://user-images.githubusercontent.com/9644867/112024366-80192f00-8b0a-11eb-9cd5-e951b0566d42.png)

**Comment by phil-lgr** [comment]
Wikipedia docs: https://en.wikipedia.org/wiki/Help:Link

**Comment by svsool** [comment]
> Would you have any clues on how to tell mdx to resolve the links created with Memo [[]] so that we can render actual pages into a docs website ?

Not familiar with remark. Memo uses markdown-it, see [this file](https://github.com/svsool/vscode-memo/blob/master/src/features/extendMarkdownIt.ts) to learn how it's implemented.

> is there any reason why you went with `[[Real Page|Page Alias]]` instead of `[[Real Page:Page Alias]]` ? the latter seems to be more in use? I'm thinking out loud

For compatibility with Obsidian.md and that users could transition more easily.

To use links within table you need to escape pipe symbol, see this issue for reference https://github.com/svsool/vscode-memo/issues/164.

**Comment by phil-lgr** [comment]
Worked with https://github.com/landakram/remark-wiki-link

```js
/**
 * remark plugin to parse [[Wiki Link]].
 * @see https://github.com/landakram/remark-wiki-link
 */
export const remarkWikiLinkPlugin = [
  wikiLinkPlugin,
  {
    aliasDivider: '|',
  },
];
```

I just had to change the alias divider, some adjustment to generated path and it's all good!

**Comment by phil-lgr** [comment]
Just for reference

![image](https://user-images.githubusercontent.com/9644867/112064298-1fedb180-8b39-11eb-9a86-c01dde651ae1.png)

Memo makes everything so nice since it takes care of updating the links in my md files, backlinks are so nice to have.

Hey maybe we should have a gatsby + remark + memo demo somewhere for reference :)

**Comment by phil-lgr** [comment]
another trick that might be useful

to convert the a tag into Gatsby Link one must use

https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-catch-links
