### ISSUE TITLE
Feature Request: Create & open tomorrow's note command

### ISSUE THREAD

**Issue by abuggin** [svsool/vscode-memo#33]
I (try to) plan an MIT for the next day.
Supporting this additional command would help my flow and I think is in line with the already supported `Open Today's note` command.

**Comment by svsool** [comment]
Hi,

It makes sense to have such possibility. I've seen you've opened a PR and code looked good me, yet I had a little bit more scalable solution in mind. What do you think about it?

![screencast 2020-07-24 20-34-32](https://user-images.githubusercontent.com/1452141/88419272-950fb800-cded-11ea-8ce7-b2c71370f4c5.gif)

**Comment by abuggin** [comment]
It's interesting but I don't think I'd use it, to be honest: I tend to open tomorrow's and today only.

For me opening the other days from the sidebar is fine: notes are already in the YYYY-MM-DD format, so it's low effort to do it that way.

On another note, I've not spent enough time with vscode extension development to understand how much effort this would require.

**Comment by svsool** [comment]
> It's interesting but I don't think I'd use it, to be honest: I tend to open tomorrow's and today only.

I see the point and I think it's possible with the suggested solution as well.

> For me opening the other days from the sidebar is fine: notes are already in the YYYY-MM-DD format, so it's low effort to do it that way.

Works less well for me, because explorer sorting asc / desc is not configurable on folder level. Finding closest dailies via quick pick easier for me. For instance, from time to time I need to check previous Mondays (because we have weeklies that day) and quick pick would come handy.

> On another note, I've not spent enough time with VSCode extension development to understand how much effort this would require.

What do you think if I will release my version of this feature, will it work for your case as well? Initially it was in my plans to get rid of `Open today's note` in favor of this more scalable quick pick solution, which also covers Tomorrow's note case. We still can keep these commands separately, however, I doubt there is a need except it saves one click in two cases tomorrow + today.

**Comment by abuggin** [comment]
I think that your version would satisfy my use case as well. 
From the screencast, I'm not sure how would you select the other days.
Would you be able to support something like `+1` and `-1` for tomorrow and yesterday maybe? 
Something like a relative number of days as input selection?

Thank you for your time :smile:

**Comment by svsool** [comment]
> Would you be able to support something like +1 and -1 for tomorrow and yesterday maybe?

I will add -1 / +1 prefixes in front of yesterday and tomorrow. Also, you can type `Yes` (yesterday) or `Tom` (tomorrow) or just use arrow up / down to reach them via keyboard. I put today, yesterday and tomorrow in the beginning of the list to make them easily reachable via keyboard and without typing anything.

> Thank you for your time 😄

Thank you for yours and sorry that your PR should be closed in favor of mine 😞.

**Comment by abuggin** [comment]
Great stuff. Don't worry. Should never be about ego anyway :smile:

**Comment by svsool** [comment]
Hi,

"Open daily note" command was released in v0.1.11, please update Memo extension to use it. Feel free to reopen this issue if something.

**Comment by abuggin** [comment]
Is there a way to create those notes in a specific folder with all the others? 
I could be missing something but I can only managed to open them in the root folder.

**Comment by svsool** [comment]
> Is there a way to create those notes in a specific folder with all the others? 
> 

"By all others" - do you mean other daily notes?

I think a new setting can be introduced for configuring default folder for daily notes. 

Do you think it would it be useful for you?

> I could be missing something but I can only managed to create them in the root folder.

Today and tomorrow commands were also creating daily notes to the root folder and new command did not change this logic.

**Comment by abuggin** [comment]
Yeah having such setting would definitely be useful.
