### ISSUE TITLE
Enhanced link in MD preview isn't standard

### ISSUE THREAD

**Issue by caiych** [svsool/vscode-memo#333]
Noticed this while using this extension in [code-server](//code-server.dev)

The enhanced link will just direct the web url out of vscode.

As a reference:
```md
[[page]]    =>    generates a link like "/absolute/path/to/page"
[page](./page.md)    => generates a link like "/webview/vscode-resorce/file///absolute/path/to/page"
```

I quickly checked just following the pattern doesn't work in normal VS Code.
(Nor does it just use the adjacent getImgUrlForMarkdownPreview)

Probably related to https://github.com/microsoft/vscode/issues/97962

**Comment by caiych** [comment]
Sure:)

My current propose is to replace the hand-crafted HTML in extendMardownIt with MarkdownIt.render(translatedMarkdownSource).
(haven't verify it's fixing the problem on code-server but it seems not breaking the usage in vscode)

What do you think?

**Comment by svsool** [comment]
I assume [this code](https://github.com/svsool/vscode-memo/blob/62dda4d452ba908d37b280cede7c235abce5569a/src/utils/utils.ts#L373-L377) along with [this part](https://github.com/svsool/vscode-memo/blob/master/src/features/extendMarkdownIt.ts#L75) should be compatible with code-server env?

**Comment by caiych** [comment]
Actually after digging it a little I think the problem is with code-server(the link doesn't work if it's an absolute path, while the same content works on VSCode). 

Filing https://github.com/cdr/code-server/issues/3124

I'm closing this issue for now hoping they can fix this in code-server and there's no work left to be done in this extension.

Thanks.
