### ISSUE TITLE
Math in preview

### ISSUE THREAD

**Issue by zcysxy** [svsool/vscode-memo#338]
Hi. Thank you so much for the great extension!

I use the preview function a lot. However my notes contain many math expressions that are not rendered in the preview. Is it possible to support math in the preview? Or it is using a built-in parser that we can do nothing about it.

![image](https://user-images.githubusercontent.com/48207708/114885504-4a314700-9e39-11eb-8649-c216b76509f3.png)

**Comment by svsool** [comment]
Hey, seems like a duplicate of https://github.com/svsool/vscode-memo/issues/305 and not easy to fix at this point.
