### ISSUE TITLE
Absolute link not working when markdown file has dot (.) in filename?

### ISSUE THREAD

**Issue by phil-lgr** [svsool/vscode-memo#339]
Hi again, 

I'm trying to figure out how to use absolute links, but I can't get it to work :

https://user-images.githubusercontent.com/9644867/115097931-13236a00-9efb-11eb-9429-58ed921cd57e.mp4

Any thoughts?

**Comment by phil-lgr** [comment]
Renaming pages.md (without the en.) it works

![image](https://user-images.githubusercontent.com/9644867/115097988-6a293f00-9efb-11eb-8194-5575831936aa.png)

**Comment by phil-lgr** [comment]
![image](https://user-images.githubusercontent.com/9644867/115098051-d0ae5d00-9efb-11eb-9ac6-239a173f41d8.png)


![image](https://user-images.githubusercontent.com/9644867/115098055-d7d56b00-9efb-11eb-9f81-d1d1fe991d66.png)

Probably something we can fix

**Comment by svsool** [comment]
Memo considers dots to be extensions as any file system and tells about it. There is no easy fix for that. If you could replace those with some other symbols, that's great.
