### ISSUE TITLE
Associate "Open link to the side" with Ctrl+shift+click

### ISSUE THREAD

**Issue by ngirard** [svsool/vscode-memo#340]
Hi,
let me start by expressing my gratitude for your efforts into this nice project !
It has much improved since I've first evaluated it last year, and it will be a nice fit in out current project's toolset. Also, as an Obsidian user, I'm feeling quite at ease, despite the inevitable missing features.

I think the biggest UX problem I encountered is that "Open link to the side" can only be triggered using the keyboard.
Given the importance of this command, I wish to propose that it is also associated with Ctrl+shift+click.
This way, a link to an image can easily be opened to the side, overcoming the absence of preview on hover.

Cheers

**Comment by svsool** [comment]
Hi,

Besides keyboard "Open link to the side can" be triggered also via context menu.

![image](https://user-images.githubusercontent.com/1452141/115298853-b0360b00-a166-11eb-9b75-ab367ee952c1.png)

> I wish to propose that it is also associated with Ctrl+shift+click.

As far as I know vscode does not support shortcuts with mouse clicks at the moment. https://github.com/microsoft/vscode/issues/38849

**Comment by ngirard** [comment]
> As far as I know vscode does not support shortcuts with mouse clicks at the moment.

Thanks for the detailed explanation. I've voted for the upstream issue: apparently the number of votes is taken into account when deciding which VS Code issues to fix first.

**Comment by svsool** [comment]
This one could be reopened as soon as there are more news on progress with it from vscode team. 👍
