### ISSUE TITLE
Unclear how to "open the help folder in VSCode"

### ISSUE THREAD

**Issue by ngirard** [svsool/vscode-memo#342]
The README advises to *"open the help folder in VSCode"*.
I have to say, I couldn't figure out how to do.
I ended up downloading the zipped shapshot of the repo and extracting in into my workspace. I guess you had something simpler in your mind.

**Comment by svsool** [comment]
Hi, I had exactly this in mind, so it seems that you figured it out and that's pretty common action for GH UI.

**Comment by ngirard** [comment]
> so it seems that you figured it out and that's pretty common action

Actually, it wasn't obvious at all, and I took the time to fill this report so that you clarified this sentence...
