### ISSUE TITLE
Feature request: Support for '.' in links

### ISSUE THREAD

**Issue by Hocnonsense** [svsool/vscode-memo#346]
I think `.` is not always at the end of a work. For example, a file is named `version0.0.1.md` can never be recognized. However, if it is created and maintained by other programs, I cannot rename it manually. Also, it is impossible to link a norm with `.` like `tar.gz`.

I guess it is caused by forward searching of `.`. If so, is it possible to find it reversely? To think more bravely, if there is a text file or any other format, we can use `![[filename.extention]]` to show its content. In general, it is worth to be fixed!

Similar request: 
- #299 
- #339

Thanks!

**Comment by svsool** [comment]
Hi, thanks for filing an issue.

Would you like to contribute?

**Comment by Hocnonsense** [comment]
I'm looking at the code, but I think I'm not familiar with TS...

I notice it is not easy as I found this:

https://github.com/svsool/vscode-memo/blob/62dda4d452ba908d37b280cede7c235abce5569a/src/utils/utils.ts#L95

**Comment by svsool** [comment]
btw `tar.gz` shouldn't be a problem it just not amongst [recognized formats](https://github.com/svsool/vscode-memo/blob/master/src/utils/utils.ts#L14-L44), formats are whitelisted for perf reasons and to scan less files on initial load.

**Comment by svsool** [comment]
should be fixed in v0.3.7 for long links

**Comment by Hocnonsense** [comment]
Thanks! It did work! Grateful for your help 😃
