### ISSUE TITLE
Add extension to open-vsx.org

### ISSUE THREAD

**Issue by CrCs2O4** [svsool/vscode-memo#349]
Hey @svsool,

thanks a lot for your extension, really enjoy using it (over dendron & foam). I'm using [VSCodium](https://github.com/VSCodium/vscodium) which is connected to [Open VSX Registry](https://open-vsx.org).

Can you publish your extensions to [Open VSX Registry](https://open-vsx.org) too? It's simple and straightforward according to [How to Publish an Extension](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions).

Thanks! 👍

**Comment by svsool** [comment]
Hi @CrCs2O4,

I'm not a user of VSX Registry.

Would you be up to contribute by modifying [ci.yml](https://github.com/svsool/vscode-memo/blob/master/.github/workflows/ci.yml) to support it?

I'll provide you with the token via GH secrets.

**Comment by CrCs2O4** [comment]
I would prefer not to open PR without actually testing it 🙂 

There is recommended [GitHub Action for Publish VS Code Extension](https://github.com/HaaLeo/publish-vscode-extension#readme) can you check it out? I assume you can directly copy-paste to `ci.yml` from it.

Thanks! 👍

**Comment by svsool** [comment]
That action seems like a super thin wrapper around ovsx, so maybe not that useful.

**Comment by svsool** [comment]
[Published to Open VSX](https://open-vsx.org/extension/svsool/markdown-memo).

**Comment by CrCs2O4** [comment]
Awesome, thanks a lot! 👍  can you also publish your other [markdown-kit](https://github.com/svsool/vscode-markdown-kit) extension?
