### ISSUE TITLE
Compatible with txt files

### ISSUE THREAD

**Issue by werunom** [svsool/vscode-memo#354]
Hello! Thanks for this nice extension. 

Since all my research notes are `txt` files (which i render in markdown format), was excited to try this extension. However, looks like most of the features do not work if the files are not `md`. E.g., even though the autocomplete for creation of link works, the `backlinks` feature does not work. That is, i do not see the linked files in the sidebar `Backlinks`.

Would it be possible to extend this extension to txt files such that all features work?

**Comment by svsool** [comment]
Hi,

I'm afraid it won't be easy, Memo is markdown knowledge base.

Consider to fork it if you want to add txt support.
