### ISSUE TITLE
Links not working (going to external browser) when clicked in markdown preview

### ISSUE THREAD

**Issue by victorkane** [svsool/vscode-memo#367]
When I do Ctrl-Click in the  `.md` source file on a wiki-link, it works fine, as expected (i.e. `[[README]]`). However, when I open markdown preview (markdown all in one plugin installed), the link is treated as external (for `[[Features]]` viewed as a hyperlink in the preview, clicking on it goes to external browser with the link `https://bfec8ed7-e44a-4b2b-b503-20b06f35a1ce.vscode-webview-test.com/home/victor/Work/AWebFactory.com/doc/vscode-memo/help/Features/Creating%20links.md`.
Is there something I'm missing in the setup for preview? Thanks so much for your wonderful plugin, that enables us to respect and enjoy open source.

**Comment by svsool** [comment]
Hi, @victorkane!

Do you use vscode in browser? Memo was not implemented with web env in mind.

**Comment by victorkane** [comment]
Thanks for answering so promptly. No, using vscode on Desktop Ubuntu 20.04, standard  `.deb` install. Sorry for being incomplete about environment I'm using. Using the following markdown extensions (vscode and extensions up-to-date):

- markdownlint
- Markdown All in One
- Markdown Memo
- Markdown Kit
- Markdown Preview Mindmap support
- Markdown Preview Mermaid support
- markdownlint

**Comment by svsool** [comment]
Maybe some other extension interferes with the links. I'd suggest to disable extensions one by one and do vscode reload to find a concrete extension that interferes.

Do you have memo's help folder opened as a workspace?

**Comment by victorkane** [comment]
Thanks for trying to help, it's a weird situation. When I can, I will disable all extensions and see what's going on, you must be right about some extension interfering.

In the meantime, as a workaround, while wiki links (created by typing `[[` and clicking on the target) are not working (i.e. [[project1]]), I find that regular markdown links (`[Projects](Projects/project1.md) ***are*** as markdown preview links.

Again, thanks for a spectacular open source and vscode based alternative to obsidian, etc., I'm using it for my Journal as of right now, and will be using it every day, so I'll let you know how it goes.

**Comment by sunny-satellite** [comment]
Hi, same problem here but also with regular markdown links [Test](test.md). This came from one of the last updates of the extension. Every link is opening within the browser and not within cs-code. My environment: VS-Code on Windows 10 64bit. The link works within the .md file but not within the preview - the preview opens the browser.
I've disabled all extensions and restartet vs-code. Same effect again. There must be something broken.

**Comment by svsool** [comment]
> Hi, same problem here but also with regular markdown links [Test](test.md).

Hi @sunny-satellite, Memo is not supposed to change behavior of regular markdown links. Did you try to disable Memo is problem still present?

**Comment by svsool** [comment]
It was fixed in v0.3.9. Please update Memo extension.
