### ISSUE TITLE
Backlinks do not work within folders

### ISSUE THREAD

**Issue by AntonioL** [svsool/vscode-memo#376]
I have this link in a Daily markdown file (saved to the root folder)
```
[[A/B/C]]
```

This link has folders inside it.

- I can create easily a new *.md via Ctrl + Click. However if I look in the Backlink section on the `[[A/B/C]]` page I cannot seem to find the relevant pages where the `[[A/B/C]]` links is mentioned.

I found out that this works with links which do not contain "folders".

I am talking about the Backlinks section in the left side bar of VS Code.

**Comment by svsool** [comment]
Hi, thanks for reporting.

Maybe I could check at some point, quite busy at the moment with regular work.

Feel free to contribute as well!

**Comment by svsool** [comment]
Hi, I checked described case and it seems to work on macOS 12.0.1 and VSCode 1.63.0. Feel free to re-open this issue if bug is still present and please attach zipped workspace and mention OS and version that you use.

<img width="50%" src="https://user-images.githubusercontent.com/1452141/145718623-f5899688-e194-49db-9069-e77f667132c9.png" />
