### ISSUE TITLE
link auto-creation

### ISSUE THREAD

**Issue by alexisargyris** [svsool/vscode-memo#4]
This is not really a bug, rather an inconvenience. If you insert a link that:

- doesn't exist yet,
- should go inside a directory
- has a unique file name

and ctrl/cmd-click to create the file, the new file is created but the link doesn't work. If, subsequently, you enter the link manually, Memo uses the short form because the link is unique.

I ended up first creating the target file and then creating the link towards it which works reliably.

**Comment by svsool** [comment]
Hi, please check if it works in v0.1.6.

**Comment by alexisargyris** [comment]
Yes! Is there a way for the link's popup to stop saying that the file is not created?

**Comment by svsool** [comment]
> Is there a way for the link's popup to stop saying that the file is not created?

I'm not sure I follow. That's how I have it:

![Issue #4](https://user-images.githubusercontent.com/1452141/87015617-53b8bf00-c1d6-11ea-9708-46cf6b5760f0.gif)

Or do you mean stop saying it in general if file does not exist?

**Comment by alexisargyris** [comment]
Yes, working 100%. Can't recreate what I described earlier. Thanks!
