### ISSUE TITLE
Embedded notes and images don't show up in preview

### ISSUE THREAD

**Issue by jowitte** [svsool/vscode-memo#431]
Images don't show up in preview any longer for me. Please see screenshot. The image exists and displays correctly when directly following the link.
<img width="987" alt="image" src="https://user-images.githubusercontent.com/8180200/125110078-6bc26780-e0e4-11eb-91f0-b55ff2b93035.png">

Any suggestions?

**Comment by svsool** [comment]
Hi,

Do you use native markdown preview or some other extension?

**Comment by jowitte** [comment]
I tried the native and markdown enhanced. Both with same results. If I hover the image in the source, it doesn’t show the image. However, if I “Follow link” it correctly shows the image.

**Comment by svsool** [comment]
Please share you environment: system version, vscode version, memo extension version and potentially other extensions installed.

**Comment by jowitte** [comment]
After disabling all extensions related to markdown it works. The “Reload Required” marked extensions is my markdown setup in vscode

Version: 1.58.0 (Universal)
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-08T06:54:17.694Z
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0

I’ll now try to reactivate extensions one by one to find the “enemy”.




I’m on Mac

**Comment by svsool** [comment]
Feel free to re-open if there is still some help needed.
