### ISSUE TITLE
Support e.g. `${currentFileDir}` in `memo.links.rules` setting

### ISSUE THREAD

**Issue by Kibouo** [svsool/vscode-memo#469]
Bigger projects require some hierarchy to keep the nodes ordered.

I have following setup:
```
- subdir
    - sub_file1.md
- main.md
```

I tried clicking a link in `sub_file1.md` to create a file and expected the new file to be placed in `subdir`. Instead it created it in the root.

So I added following config:
```json
"memo.links.rules": [
    {
        "rule": "\\.md$",
        "comment": "All notes",
        "folder": "${currentFileDir}"
    }
]
```

But now it created a new dir literally called `${currentFileDir}` with the note in it. 

Does vscode-memo use a different keyword? Or is this not supported? I could have a look at implementing `${currentFileDir}`.

**Comment by svsool** [comment]
> Does vscode-memo use a different keyword? Or is this not supported? I could have a look at implementing ${currentFileDir}.

This is not supported at the moment. I think similar concept could be borrowed as with [variables](https://code.visualstudio.com/docs/editor/userdefinedsnippets#_variables) in VSCode snippets.

**Comment by svsool** [comment]
Hi, this feature should be available in the latest version. Please update from Marketplace!

Supported vars:
![image](https://user-images.githubusercontent.com/1452141/146676623-083009b9-6b33-4556-8f17-4742a93cd9bd.png)


Read more [here](https://github.com/svsool/vscode-memo/blob/master/help/Features/Creating%20notes%20from%20links.md#link-rules).
