### ISSUE TITLE
can't preview image in edit mode

### ISSUE THREAD

**Issue by tswwe** [svsool/vscode-memo#471]
* OS: Win10 (10.0.19043)
* VSCode Version: 1.59.1 (Portable)
* Description:
    The pop-up previewer in edit mode works on previewing embedded notes, but fails previewing embedded images. Instead, it shows a broken image icon.
I have tried many image files (of different formats), but none of them can be previewd.

![77nOTdtFzI](https://user-images.githubusercontent.com/36465489/131253244-b68a061a-2d96-445a-b35d-0cb38c553363.gif)

**Comment by heyheyhello** [comment]
Have you tried a relative path to the image? `![](./assets/img.png)`?

**Comment by tswwe** [comment]
Yes, I have tried different forms of path, though none of them works.

Here is a more specific screenshot (other plugins except Memo are disabled in case of disturbing):
![SiR9Ylrnmo](https://user-images.githubusercontent.com/36465489/131434187-613d08fa-6f60-4628-a8e8-03ebb3ff3027.gif)

And this is my workspace archieve, if needed: [VXCode.zip](https://github.com/svsool/vscode-memo/files/7080782/VXCode.zip)

**Comment by svsool** [comment]
Hi, seems to work with VSCode: 1.63.0 and macOS 12.0.1, feel free to re-open if it still doesn't.

![image](https://user-images.githubusercontent.com/1452141/145717633-dd3c5298-ba27-4ea5-a256-c60ae13518a5.png)
