### ISSUE TITLE
Note Preview in Link Completion

### ISSUE THREAD

**Issue by zcysxy** [svsool/vscode-memo#472]
Thanks for this great plugin. I have a small feature request, that is showing note preview when we type wiki link in the editor. This feature is implemented in [Markdown Notes](https://github.com/kortina/vscode-markdown-notes) (which I don't use because its performance on large repo is very slow). Since IMO Memo has a better preview feature than Markdown Notes, I think it would be great to also enable preview feature in the link completion.

![image](https://user-images.githubusercontent.com/48207708/131280798-30b21908-a933-4fe2-b172-9a00e258d7f6.png)

**Comment by svsool** [comment]
Hi, this feature should be available in the latest version. Please update from Marketplace!

Notes preview:
![image](https://user-images.githubusercontent.com/1452141/146643216-1f2177ea-8449-446f-9eea-556893aba4f4.png)

Images preview:
![image](https://user-images.githubusercontent.com/1452141/146643220-c8ddd488-28c3-481f-9402-fae0109bb5dd.png)
