### ISSUE TITLE
Command to wiki-linkify selected text

### ISSUE THREAD

**Issue by srid** [svsool/vscode-memo#474]
To add wiki-link to some text, I currently follow an inefficient process:

- Move the cursor to beginning of text that needs to be linked
- Insert `[[` to trigger autocomplete
- Type the first few letters to arrive at the desired note (this doesn't work reliably when your filename has spaces, but that's a different bug to report)
- Hit 'enter' on the selected note to insert the link
- Press right arrow multiple times to go to the end of the text that needs to be linked
- Insert `]]`
- Confirm in markdown preview that the added link is valid

As you can see this is needlessly laborious. I suggest adding a vscode command (involved in <kbd>Ctrl+Shift+P</kbd>) that will automatically do this on *selected text* by offering the user a pop-up for selecting the target note. This popup could re-use the same UI used by the <kbd>Ctrl+Shift+P</kbd> UX. 

What do you think, @svsool ? I wonder if I'm missing some other workflow here that would obviate this idea. Really enjoying this extension for working with [Emanote](https://note.ema.srid.ca/) notes!

**Comment by svsool** [comment]
Hi, if I understood correctly you want to select some arbitrary text and add a wiki-link somewhere (before/after selected text?) by picking it from pop-up. Is it any different from just adding a wiki-link in front of the text without selecting the text?

**Comment by svsool** [comment]
Will close it for now, feel free to re-open in case of more input coming.
