### ISSUE TITLE
Backlinks context is not very informative

### ISSUE THREAD

**Issue by memeplex** [svsool/vscode-memo#478]
The backlinks panel shows an expanded lists of backlinks inside each note that links to the current one. Each backlink is shown with some context, namely the text immediately following it. Since the panel is relatively small and each backlink uses extra space, it's important for this context to be informative, otherwise a collapsed view showing only notes would be preferable by default.

![image](https://user-images.githubusercontent.com/2845433/139479946-0122b735-86cb-4450-9aa0-a496734368fd.png)

This image was taken from vscode-memo help but I believe it's representative of a common situation: 

> You can embed any other note, for instance: ![[Features]]

> Or you can embed an image: ![[Backlinks panel.png]]

> Continue to [[Features]].

It's too common for the relevant context to be before the link and not after it.

I would prefer that the backlinks view were collapsed by default, I find it too noisy as it is now. OTOH it would be great if before or around context were shown.

**Comment by memeplex** [comment]
I've given this a little more thought. This is the information currently shown:

1. Column number
2. Line number
3. Link content
4. Snippet of text following link

Regarding 1 and 2 I'm unable to figure out how could they be useful. Regarding 3 most of the time it just repeats the name of the current note, so again provides no useful clue, although when there is a link description this might be the more valuable piece of context. Regarding 4 I've already done some commentary.

FWIW my suggestions are:

1. Remove column, line and link
2. If there is a link description use it as context
3. Otherwise pick the text around and show something like `this is before [[...]] this is after`
4. Start with a collapsed view or add an option to start it collapsed

**Comment by svsool** [comment]
Hi

> I would prefer that the backlinks view were collapsed by default

There is this option in the settings (I hope it helps):

![image](https://user-images.githubusercontent.com/1452141/139529511-e4e92543-cfd5-420c-a66d-3e99accdac72.png)

Also there is this issue https://github.com/svsool/vscode-memo/issues/104 open which is probably similar.

**Comment by memeplex** [comment]
> There is this option in the settings 

Oh, great, thanks! I'd scanned the entire config at the beginning but this concern wasn't in my mind at the time.

> Also there is this issue #104 open which is probably similar.

Sure it is, I'm closing this one then.
