### ISSUE TITLE
Can't open hyperlinks in the built-in markdown preview

### ISSUE THREAD

**Issue by SuperSASS** [svsool/vscode-memo#481]
When I click the hyperlink of [[link]] in the built-in VSCode Markdown preview, it can't be opened because the path of linked file is wrong, as the working directory will be added to the front of the path.

> For example:
>
> ![1](https://user-images.githubusercontent.com/32005046/140555830-c4413c20-6063-4f1e-939e-7fac2efc533f.png)
>
> After I click the hyperlink "Tips" in markdown preview, an error will pop up.
>
> ![2](https://user-images.githubusercontent.com/32005046/140555846-6b0862cc-5f0a-4baa-af06-df5c1261524b.png)
>
> You can find the additional working directory as the underlined part.

* OS: Windows 10 21H1 (The same problem happened in Windows 7, either)
* VSCode version: 1.62.0

I have disabled all extensions for markdown but the problem still remains.

---

However, I found it works fine on my Linux system.

![linux_welldone](https://user-images.githubusercontent.com/32005046/140555862-9e2857f9-3a43-42f7-8370-aa237bd27e91.gif)

Moreover, I found if I use ![[link]] and click the hyperlink icon on the right, it will open the browser with the address: `https://file+.vscode-resource.vscode-webview.net/(file path)`

![linux_problem](https://user-images.githubusercontent.com/32005046/140555856-cf0f96cb-f96f-479d-9fde-86796e14a66b.gif)

In the system above(Windows 10), nothing happens when click this icon.

![windows](https://user-images.githubusercontent.com/32005046/140557540-bd57e3f6-f002-46c5-ae1a-d0516b016c44.gif)

**Comment by svsool** [comment]
Hi, thanks for reporting. 

Seems like a Windows specific problem. Last time I tested this extension it worked fine under Windows, so it could be related to some recent updates in VSCode. Likely logic [here](https://github.com/svsool/vscode-memo/blob/eba15fc0692fefb0a0f94aea761a04282e18e2f3/src/features/extendMarkdownIt.ts#L113) and [here](https://github.com/svsool/vscode-memo/blob/eba15fc0692fefb0a0f94aea761a04282e18e2f3/src/features/extendMarkdownIt.ts#L77) should be checked.

Do you btw use latest version of this extension?

**Comment by antulik** [comment]
I'm experiencing same issue

Mac Monterey 12.0.1 
VS Code Version: 1.62.3
Memo Version: v0.3.9

**Comment by proItheus** [comment]
The same issue in Arch linux : `无法读取文件'/home/proitheus/Documents/vscode-memo/home/proitheus/Documents/vscode-memo/help/Features/Features.md' `

**Comment by svsool** [comment]
Hi, it seems that internal logic for resolving links changed once again in VSCode inside markdown preview.

This problem should be fixed in the latest version of Memo (tested under macOS and Windows). Please update from Marketplace!
