### ISSUE TITLE
Is it possible to specify a folder configuration for open daily notes?

### ISSUE THREAD

**Issue by faydanube** [svsool/vscode-memo#482]
It works really well for me as all the diaries are in a separate folder

@svsool

**Comment by svsool** [comment]
Hi, yes it's possible, please find an example [here](https://github.com/svsool/vscode-memo/blob/master/help/Features/Creating%20notes%20from%20links.md#link-rules).

**Comment by faydanube** [comment]
> Hi, yes it's possible, please find an example [here](https://github.com/svsool/vscode-memo/blob/master/help/Features/Creating%20notes%20from%20links.md#link-rules).

it works.

Is it possible to support a simpler implementation, such as the configuration of foam: 
```json
"foam.openDailyNote.directory": "journals",
```
