### ISSUE TITLE
Link out to another workspace

### ISSUE THREAD

**Issue by jklymak** [svsool/vscode-memo#483]
Thanks a lot for this extension - it seems are really great way to use Obsidian-like workflow directly in vscode.  This may be more general to markdown, but since this is a note-taking extension, I thought I'd ask here.

I have lots of vscode workspaces.  It would be _great_ for note keeping if I could somehow link those from the Markdown so that the workspace opened in vscode.  i.e. something like `[[vscode:/Users/jklymak/my-cool-workspace/]]` and following that link would open that vscode project (just like running `code /Users/jklymak/my-cool-workspace` would fro the command line.  

Any hints here?  A search for such an extension didn't turn anything up, but there are a _lot_ of markdown extensions.   Thanks!

**Comment by svsool** [comment]
Hi, as far as I know vscode support hyperlinks format like following `[link](vscode://file/path/to/workspace)`. See [this](https://stackoverflow.com/questions/48641921/is-it-possible-to-use-the-vscode-hyperlink-to-open-a-file-or-directory-in-code) answer.

**Comment by jklymak** [comment]
Ha I'd never have guessed the "file" part of that.  Sorry to be off topic, and thanks again for the extension - it is very nice!
