### ISSUE TITLE
Parens in file names break backlinks

### ISSUE THREAD

**Issue by harveyr** [svsool/vscode-memo#5]
Moving over from Obsidian, I have filenames like `Black Swan (book).md`. Those parens seem to break the backlink code. 

I'm just going to update the names, since parens are ugly anyway. So no rush. 

I'm really liking the extension!

**Comment by svsool** [comment]
Thanks for reporting. Let me know if fixed in v0.1.7.

**Comment by svsool** [comment]
I will close it for now. Let me know if anything.

**Comment by harveyr** [comment]
Just tested it and it seems to work! Thank you!
