### ISSUE TITLE
How to change bright red colour of links without target

### ISSUE THREAD

**Issue by erikjalevik** [svsool/vscode-memo#519]
In my PKM, I make frequent use of links that don't yet have a target page. These show up as a bright red in the markdown preview in the default dark VSCode mode and are pretty hard on the eye:

<img width="552" alt="Screenshot 2022-01-27 at 08 35 22" src="https://user-images.githubusercontent.com/8722592/151312500-74878410-2d02-4b80-8c30-077163af4942.png">

Is there a way to actually configure these to be a different colour? I played around with adding custom CSS via VSCode's workspace setting but CSS doesn't have a method for targeting "broken" links, so I can change the colour only of the links that already have a target.

**Comment by svsool** [comment]
hi, I tried [this approach](https://code.visualstudio.com/docs/languages/markdown#_using-your-own-css) with following css and colour override works. Similar question was asked [here](https://github.com/svsool/vscode-memo/issues/226).

```
.memo-invalid-link {
  color: #a19700 !important;
  cursor: not-allowed;
}
```

![image](https://user-images.githubusercontent.com/1452141/151580183-6c8ca295-0d40-4c49-93a5-408697ef0256.png)

I hope this helps.

**Comment by erikjalevik** [comment]
Fantastic, that does the trick!
