### ISSUE TITLE
Follow link is not working with Memo [[Links]]

### ISSUE THREAD

**Issue by pmagwene** [svsool/vscode-memo#520]
## VS Code Details

Version: 1.63.2
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:37:28.172Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 19.6.0

## To recreate

Start a simple markdown document and try and create text with `[[links]]` or `[[links.md]]`; The text in the brackets turns blue and a "Click to create" dialog appears on mouse hover but "Cmd-click" doesn't do anything. Also, expected autocompletion isn't working.

**Comment by svsool** [comment]
hi, I can't reproduce this problem, does it happen with all other extensions disabled?

**Comment by ricardonunesdev** [comment]
Hi @svsool,

I'm also having this problem in Ubuntu 20.04, with no other extensions enabled.

Best regards

**Comment by svsool** [comment]
That's how it goes for me on macOS with VS Code 1.63.2.

![screencast 2022-01-28 20-08-53](https://user-images.githubusercontent.com/1452141/151599457-2c1035bd-816f-4137-96ac-79077a98a1e0.gif)

**Comment by pmagwene** [comment]
I think I've been able to determine the key factor -- the issue seems to be whether the working file (e.g. `test.md`) is in a  folder (i.e. ?workspace -- I'm not quite sure I've got the VS Code terminology usage correct here) or created in a non-folder situation.  

* If I drag an empty folder to VS Code, create a `test.md` document and follow the steps that @svsool does above than I'm able to create the new `link.md` document as show in the animation
* 
* However, if I fire up VS Code instance, create and save an empty file named `test.md`, and then add `[[links]]` I get the dialog on mouse over but I can't click to create link.md

So something about being in a folder/workspace seems to be the key to this bug.

**Comment by svsool** [comment]
Memo works only inside folders and workspaces, so please ensure to have one for your knowledge base.

**Comment by ricardonunesdev** [comment]
I found another reason why this might not work in some contexts.

If you have the `multiCursorModifier` set to `ctrlCmd` in your settings it will not work:
```
"editor.multiCursorModifier": "ctrlCmd"
```

By changing this setting to `alt` it allows VSCode to trigger the next setting for the Ctrl+Click keybinding, which is `goToDefinition`, so the previous setting should look like this:
```
"editor.multiCursorModifier": "alt"
```

You also need to have this setting enabled `Editor: Links`
![image](https://user-images.githubusercontent.com/9913683/151775176-35767f0b-4639-4fe3-a232-b773693d5803.png)

And now it works.

**Comment by ricardonunesdev** [comment]
Another solution for Ubuntu/Unity is to change to window drag/resize keybinding from `<Alt>` to something else (I chose `<Super>`) and now the `alt` key works for links without changing the `editor.multiCursorModifier` (keeping it at `ctrlCmd`).

Source: https://askubuntu.com/a/521444
