### ISSUE TITLE
Set base directory for notes

### ISSUE THREAD

**Issue by srid** [svsool/vscode-memo#542]
I keep my notes in a Git repo, but the .md notes themselves live in a subdirectory. For example, [`./content`](https://github.com/srid/srid/tree/master/content).

Is there a way to tell vscode-memo to look only under this sub directory for notes, and use that to create new notes?

I could open the subdirectory as folder in VSCode, but I do need to open the top-level project root because of .nix files that I'll be using as well (to run Emanote).

**Comment by svsool** [comment]
Workspace root is the one that used by Memo to create workspace cache and manage paths, having a separate one is a bit against vscode's design, so I'd rather not introduce this complexity in Memo to manage this particular case.

One option is to try https://code.visualstudio.com/docs/editor/multi-root-workspaces.

**Comment by srid** [comment]
> One option is to try https://code.visualstudio.com/docs/editor/multi-root-workspaces.

This didn't help; ctrl+click'ing missing wikilinks continue to create new notes in root directory.  

If anybody reading this thread have found a solution, please let me know.

**Comment by ez4gis** [comment]
I'm using `memo.links.rules` in my **workspace** settings to direct where the new wikilink notes are stored. It's not perfect but works ok for me so far.  (in my case, new wikilink note would always get stored inside the first root folder, though in a correct subfolder as specified in the rules. This isn't an issue for me though as I mostly wanted to create new notes in my first root folder anyways).    @srid 

```json
   // ...

  "memo.links.rules": [
    {
      "rule": "(\\d{4}-(0[1-9]|1[0-2])-((0[1-9]|[12][0-9]|3[01]))(_(Mon|Tue|Wed|Thu|Fri|Sat|Sun))?)\\.md$",
      "comment": "Daily notes yyyy-mm-dd_Day",
      "folder": "/journals/_daily"
    },
    {
      "rule": "(\\[Mm]d{4}(0[1-9]|1[0-2])((0[1-9]|[12][0-9]|3[01])))(_([\\s\\S]*))?(\\.md)?$",
      "comment": "Meeting notes yyyy-mm-dd_Day",
      "folder": "/journals/meetings"
    },
    {
      "rule": "\\.md$",
      "comment": "All other notes",
      "folder": "/journals/notes"
    }
  ],
```
