### ISSUE TITLE
Link icon of the embedded section is missing when exporting to html/pdf

### ISSUE THREAD

**Issue by BIKA-C** [svsool/vscode-memo#549]
Hi, I am using the [Markdown Extended](https://github.com/qjebbs/vscode-markdown-extended) to export md to pdf file since it is the only extension I found to have the What You See is What You Get export feature (I tried a few other popular md export extensions such as [MPE](https://github.com/shd101wyy/vscode-markdown-preview-enhanced), or [Markdown PDF](https://github.com/yzane/vscode-markdown-pdf), they all failed to support this powerful Mark Memo extension entirely). The only issue is that it looks like some the icon is missing when exporting the page to a self-contained html/pdf: 

### HTML
<img width="1552" alt="Screen Shot 2022-04-12 at 5 25 01 PM" src="https://user-images.githubusercontent.com/50717946/163075632-93172421-91a6-4933-9819-b4b90855a1ef.png">

### PDF

![image](https://user-images.githubusercontent.com/50717946/163075729-168679ab-eae0-4d2b-9b7c-d184bd5965a1.png)

I didn't figure out why it is missing. I really wish this can be fixed. Or is there anyway to probably disable this icon when exporting to pdf or html since it becomes less helpful when the md is exported to a document anyway?

**Comment by BIKA-C** [comment]
Just to clarify, it would be nice to have a switch in the setting to disable the link tag temporarily for the time the md needs to be exported.

**Comment by BIKA-C** [comment]
nvm, I just realized I can achieve this by overriding the css. But it is still a bit inconvenient. Having a switch would be nicer 😃

**Comment by svsool** [comment]
hi, probably approach described [here](https://github.com/svsool/vscode-memo/discussions/514) might be the best option so far, I don't think there is any export plugin in vscode marketplace that would be fully compatible.
