### ISSUE TITLE
BUG: Embedding notes don't support chinese?

### ISSUE THREAD

**Issue by destinyd** [svsool/vscode-memo#55]
## Content
```
![[自我觉知的神经学]]

![[5W1H]]
```

## Screenshots
![image](https://user-images.githubusercontent.com/68806/89607894-32ff8a00-d8a6-11ea-970b-e7299bd68251.png)

**Comment by svsool** [comment]
Thanks for reporting,

I think it does.

Do you use `.md` in filename of `自我觉知的神经学`?

![image](https://user-images.githubusercontent.com/1452141/89621900-cd59d080-d89a-11ea-88ef-0d13d49d1944.png)

![image](https://user-images.githubusercontent.com/1452141/89621953-e793ae80-d89a-11ea-9206-a09da967c400.png)

![image](https://user-images.githubusercontent.com/1452141/89621929-dd71b000-d89a-11ea-9248-dc7910866f6b.png)

**Comment by destinyd** [comment]
> Thanks for reporting,
> 
> I think it does.
> 
> Do you use `.md` in filename of `自我觉知的神经学`?
> 
> ![image](https://user-images.githubusercontent.com/1452141/89621900-cd59d080-d89a-11ea-88ef-0d13d49d1944.png)
> 
> ![image](https://user-images.githubusercontent.com/1452141/89621991-fc704200-d89a-11ea-8e27-e95199c856bc.png)
> 
> ![image](https://user-images.githubusercontent.com/1452141/89621929-dd71b000-d89a-11ea-9248-dc7910866f6b.png)

Thanks for your reply.

I think it has cyclic link.

**Comment by svsool** [comment]
> I think it has cyclic link.

Cyclic links are [detected](https://github.com/svsool/vscode-memo/blob/master/src/features/extendMarkdownIt.ts#L81) as well.

![image](https://user-images.githubusercontent.com/1452141/89637231-8aa3f280-d8b2-11ea-9fdb-29b3bcf35cb3.png)

![image](https://user-images.githubusercontent.com/1452141/89637214-84157b00-d8b2-11ea-8361-8c1855613273.png)
