### ISSUE TITLE
Links labelling doesn't work

### ISSUE THREAD

**Issue by ansidev** [svsool/vscode-memo#550]
Please fix the feature Link labelling. (Line 5 is not rendered as expected)

![Screen Shot 2022-04-21 at 04 00 18](https://user-images.githubusercontent.com/6688235/164322215-4f01e74a-35ba-4b8c-9c58-6cbee4535acc.png)

**Comment by svsool** [comment]
do you use native markdown preview or some other plugin? Memo works with the native one only.

**Comment by ansidev** [comment]
@svsool OK, I got it! Thank you very much!
