### ISSUE TITLE
Feature Request: option to rename link to rename file and other references to the file

### ISSUE THREAD

**Issue by sahil48** [svsool/vscode-memo#6]
After reviewing the resume, I see that when a file is renamed, references to it from other files are renamed accordingly. I think it would also be nice to have a hyperlink in the pop-up when you hover over a link to rename the corresponding file and other references to it. I think it would work really great for renaming images and other attachments in the future more easily.

**Comment by svsool** [comment]
Hi,

Currently Memo syncs according links on file rename, and you propose to do it other way around - hover link under cursor -> click rename from popup -> rename file and links, is that correct? For now you can use combination of follow link and file rename as a workaround. I think proposed feature copies partly or fully functionality that already exists in Memo. I can imagine that it will be just less clicks to do it via popup, but I'm not sure.

**Comment by sahil48** [comment]
That's the idea. Just to do it with less clicks and keep the file list in the sidebar focused on the current document.

**Comment by svsool** [comment]
Tried to implement links rename using VSCode rename symbol feature:

![1](https://user-images.githubusercontent.com/1452141/87699221-3ae37700-c79d-11ea-915a-b790a29be547.gif)

Still needs some work for absolute links and figuring the least way of interference with links sync of file rename which triggered by filesystem watcher.

**Comment by svsool** [comment]
v0.1.9 should supports link rename feature right in the editor either via context menu or by executing `Rename Symbol` command / hitting `F2`:

![Automatic link synchronization 2](https://user-images.githubusercontent.com/1452141/88338210-b23a7d00-cd40-11ea-8229-ff25f5616eaa.gif)
