### ISSUE TITLE
Tags support

### ISSUE THREAD

**Issue by vanadium23** [svsool/vscode-memo#60]
According to comparison with [foam](https://github.com/svsool/vscode-memo/issues/9#issuecomment-658346216) there is no tags support in vscode-memo.
Can we add this feature to roadmap?

**Comment by svsool** [comment]
Hi, 

Good that you asked.

The reason for tags support missing is that I did not find any benefits over wiki links.

**Comment by vanadium23** [comment]
How do you deal with several articles over one main theme without glossary?

**Comment by svsool** [comment]
I use dangling links for that `[[learning]] [[work]] [[books]]` without creating them to the disk + Find all references command.

When time to add details comes, I add a file by following a link.

![image](https://user-images.githubusercontent.com/1452141/90153375-92233a00-dd91-11ea-9d3b-27c2889595ba.png)

**Comment by svsool** [comment]
I use dangling links for that `[[learning]] [[work]] [[books]]` without creating them to the disk + Find all references command.

When time to add details comes, I add a file by following a link.

![image](https://user-images.githubusercontent.com/1452141/90154004-4c1aa600-dd92-11ea-9b56-9c137096858f.png)

**Comment by vanadium23** [comment]
Seems cool, thanks.

**Comment by wbgt** [comment]
What if I want the intersection? I mean how can I locate 2020-08-13.md using both [[work]] and [[learning]], for example?

**Comment by svsool** [comment]
> What if I want the intersection? I mean how can I locate 2020-08-13.md using both [[work]] and [[learning]], for example?

I think search features are out of the scope of this issue and not something that Memo is good at. Currently, I'd use regex pattern matching and built-in search for that. In the long term, perhaps a filtering panel could be introduced to filter links using boolean logic, which should be more user friendly and (maybe) less flexible/powerful than regular expression 🙂.

**Comment by wbgt** [comment]
Thank you, I understand. By the way, I have used vscode-memo for a while, I love it. However, with the files cumulated (thousands of them in my subject, and increasing), the time for getting backlinks significantly increases, due to more and more disk access. Do you have any idea about that?

**Comment by svsool** [comment]
> Thank you, I understand. By the way, I have used vscode-memo for a while, I love it. However, with the files cumulated (thousands of them in my subject, and increasing), the time for getting backlinks significantly increases, due to more and more disk access. Do you have any idea about that?

Thanks for your feedback on Memo, that's valuable. About backlinks slowness, this was [mentioned](https://github.com/svsool/vscode-memo/issues/1#issuecomment-655004112) by me before. Full-blown indexing should improve performance, but is not a trivial functionality to implement, in Memo's case it is sort of a cache and caching is a hard problem for many reasons. I think it's out of the scope of this issue. Please open another issue and describe your problem there, along with the size of your knowledge base.

For now I will close this issue. Author could reopen it if there is something to add on tags support vs wiki links.

**Comment by joellti** [comment]
> > What if I want the intersection? I mean how can I locate 2020-08-13.md using both [[work]] and [[learning]], for example?
> 
> I think search features are out of the scope of this issue and not something that Memo is good at. Currently, I'd use regex pattern matching and built-in search for that. In the long term, perhaps a filtering panel could be introduced to filter links using boolean logic, which should be more user friendly and (maybe) less flexible/powerful than regular expression 🙂.

I would love to see filtering panel on your roadmap. With files growing this becomes more of the priority to have. Thx for your consideration.

**Comment by t1u1** [comment]
> I use dangling links for that without creating them to the disk + Find all references command.

So, to support tags, can you automate this? That is, when we click a tag, it should automatically start a `find all references` command.

Supporting Tags would be useful for those migrating from other tools such as Obsidian.

**Comment by vanadium23** [comment]
@t1u1 I've make a separate plugin to support hashtags: https://github.com/vanadium23/markdown-hashtags
