### ISSUE TITLE
Actively maintained

### ISSUE THREAD

**Issue by DutchPete** [svsool/vscode-memo#647]
The last update was in 2022, and the last reply by the dev was on Jan 31st of this year. This gives me the impression this extension is not actively maintained anymore, or it could be abandonware.
Could you please tell me what the status is?

**Comment by svsool** [comment]
hi, it achieves intended functionality for the original needs it was designed to meet, maintenance is mostly done on a bugfix basis or addressing version incompatibilities, thanks!
