### ISSUE TITLE
Feature request / question: key binding for preview link?

### ISSUE THREAD

**Issue by harveyr** [svsool/vscode-memo#65]
I don't know if this is possible, so please forgive the request if it's not.

I love the preview-on-hover behavior! And I'd love it even more if I could trigger the preview of a link under my cursor with a key binding. Is this plausible? Is it the kind of thing that you'd accept a PR for?

Thanks!

**Comment by svsool** [comment]
Hi,

Show hover (`editor.action.showHover`) command should work for you, usually "cmd + k" or "cmd + i" on macOS.

![screencast 2020-08-16 11-59-33](https://user-images.githubusercontent.com/1452141/90330855-a1380100-dfb8-11ea-8441-766ed10b4b09.gif)

**Comment by harveyr** [comment]
Perfect, thank you!
