### ISSUE TITLE
Feature Request: links to PDFs and other documents by filename

### ISSUE THREAD

**Issue by sahil48** [svsool/vscode-memo#7]
Similar to images, please allow PDFs and other references to be referred to in the ![[filename.ext]] syntax

**Comment by svsool** [comment]
Hi,

Support for embedding markdown files was released today in v0.1.8 version, so you can test it out by updating Memo via the marketplace. 

About PDF support, how important is it for you to support PDF and what are the use cases? Embedding PDF requires additional effort to make the built-in Markdown preview work. As far as I know, WebKit allows you to embed PDF into HTML page, but it's a very basic PDF viewer, and you can't expect decent UX that some well-known PDF viewers / editors usually provide.

**Comment by sahil48** [comment]
I was simply hoping that selecting the PDF or word document would open it in the default application for further editing. An embedded document viewer is not necessary, just the ability to open it from the link entered in the markdown file.

**Comment by svsool** [comment]
Alright, I started to think about "embedding" because you mentioned this `![[filename.ext]]` syntax with `!` in the beginning which is used for embedding files instead of `[[filename.ext]]` which is used for linking them 🙂 . I'll check if VSCode allows opening links in the default editor.

**Comment by Annegrim** [comment]
Not sure if this fits OPs request, but I keep PDFs in my project folder, open them with the vscode-pdf extension, and then comment on them. My use-case is academia, i.e. citations and annotations.

[My hope is to be able to use *memo* (or *foam*) and create a ~~perfect~~ good enough work-flow to efficiently chew through PDFs and create my own Zettelkasten. *memo* has the better features (imo), but i am missing some graph visualization.]

**Comment by svsool** [comment]
> Not sure if this fits OPs request, but I keep PDFs in my project folder, open them with the vscode-pdf extension, and then comment on them. My use-case is academia, i.e. citations and annotations.
> 
> [My hope is to be able to use _memo_ (or _foam_) and create a ~perfect~ good enough work-flow to efficiently chew through PDFs and create my own Zettelkasten. _memo_ has the better features (imo), but i am missing some graph visualization.]

Thanks for mentioning vscode-pdf extension, it changed my mind a bit about how this feature can be used, so I'm going to implement a feature for opening any link to the existing file in the default app via additional command, otherwise on `cmd + click / enter` file will be opened in VSCode and displayed via supported plugins such as vscode-pdf.

**Comment by svsool** [comment]
v0.1.9 should support `Open link in the default app` command. Also new [document formats](https://github.com/svsool/vscode-memo/blob/467d711981b787de0b096bf84efd4bf37f2e5ae1/src/utils/utils.ts#L18) including `pdf` were added to autocomplete results.

![Opening links in the default app](https://user-images.githubusercontent.com/1452141/88338696-663c0800-cd41-11ea-9a6a-47686617d4f7.gif)
