### ISSUE TITLE
Functions to open link in adjacent/new pane 

### ISSUE THREAD

**Issue by nixsee** [svsool/vscode-memo#81]
I'm aware that there is a VS Code command/shortcut for moving a file to another editor pane, but it would be nice if we could Ctrl+Shift+Click or Ctrl+Shift+Enter to open a link in the adjacent pane. Perhaps Ctrl+Alt+Shift+Click  to open in a new pane as well, or however we choose to configure it. 

Thanks!

**Comment by svsool** [comment]
Thanks for the idea. I think four separate commands could be added, which will be proxied via [openDocumentByReference](https://github.com/svsool/vscode-memo/blob/master/src/commands/openDocumentByReference.ts) command to cover all cases: `openLinkToLeft/Right/Top/Bottom` and then shortcuts can be configured. Sounds like a good first issue, I'd wish someone would contribute.

**Comment by nixsee** [comment]
I wish I knew how to contribute code! Hopefully my ideas are mostly helpful though!

**Comment by ez4gis** [comment]
I have a first attempt at this in PR #252.  Please review and advise.  Thanks.

**Comment by svsool** [comment]
This feature was released in v0.3.3 🚀 . Special thanks go to @ez4gis for implementing it! 👍
