### ISSUE TITLE
Reverse link function

### ISSUE THREAD

**Issue by nixsee** [svsool/vscode-memo#82]
This is related to the extract/refactor request I've made that you are working on in Markdown Kit, but I think is more appropriate here as it is purely link-based.

I'm currently creating various indexes that point to my notes. It would be really neat if there was a command that uses a search/autocomplete to create a link to the current file in the OTHER selected file. It is essentially the reverse of the current wikilinking function, where a link to the other file is created in the current file. It would need to go in some default place in the target file - in a YAML header above "---" perhaps?

Another related idea - some sort of Ctrl+Shift+Click feature to create a link to the current page in the page contained within the link that was clicked on (e.g. Page 1 has [[Page 2]] within it. This command would add [[Page 1]] to Page 2.

These features would be useful for making topical index notes - I have many index pages like "Inbox", "Nutrition", "Finance" which are full of links to specific pages on those topics. If I am on a new page on Vitamins that is not yet linked to Nutrition, I could add that link without having to open and type it. Or, in the header of Vitamins, I could manually add link in the header to Nutrition and Shopping List, and then create links in those summary pages by clicking. 

I know there are backlinks, but this is an extra level of functionality.

**Comment by svsool** [comment]
Hi,

I understand the use case. For now it looks like it saves a few clicks in favor of supporting an individual flow. I'd let this idea to wait and collect more suggestions before approaching any implementation.

> It is essentially the reverse of the current wikilinking function, where a link to the other file is created in the current file.

In case of forward links, it's obvious where exactly link is created (user types it), whereas in case of reverse links it's not. There are plenty of ways to do that: send to the beginning/end of the file, put within yaml header, and so on. In general, considering the flexibility of Markdown I see little automatization opportunity for that so far, or such automatization would favor one's opinions over others and thus individual extension fits better for such.
