### ISSUE TITLE
Feature request: Find backlink file references in standard markdown links []() in addition to wiki links  [[]]

### ISSUE THREAD

**Issue by michael-guimet** [svsool/vscode-memo#83]
Thanks for Memo, it's really useful!

Currently, backlinks to other notes are only detected if wiki links are used: `[[filename]]` or `[[filename|link text]]`

Unfortunately, I upload my note to Github and where wiki links are not supported and I have a tendency to use standard markdown links `[link text](filename.md)` for notes to be usable on the web. However, doing this means backlinks are not detected.

Would it be possible to detect backlinks to files in the `[]()` link format?

Thanks.

**Comment by michael-guimet** [comment]
This might not be the best solution to the use case as an alternative way to put it could be: "Make wiki links work in Github / Markdown parsers". This might be outside the scope of the Memo project.

**Comment by svsool** [comment]
In general, it should be possible, although I think supporting backlinks is just a beginning and some other features would be good to have like links autocomplete (I believe supported already?), preview, update on rename, find by reference and so on. It sounds like enough work for the whole another extension 🙂. In many cases, I find wikilinks more compact, easier to read, and write than Markdown links, but as you mentioned so far wikilinks' portability is not the best. I wish Memo would support native links as good as wikilinks, but it would require significant time for me to implement them, so I hope more contributors could emerge, and this whole idea can be taken forward.

Here also some difference between them:

Wikilinks:

- Absolute (relative to workspace) paths supported
- Short paths supported
- Files embedding
- Easier to sync on rename
- Backlinks
- Find by reference
- Preview on hover
- Not supported by popular Markdown Viewers including GitHub

Markdown links:

- Requires relative/absolute paths
- File paths should be url encoded (raw space and other symbols are not allowed)
- No embedding
- Supported by all Markdown Viewers

**Comment by michael-guimet** [comment]
Thanks for the reply. I understand your position. In any case, I've found a few workarounds for the time being. 

I'll see how I can help, but unfortunately I'm not a node developer.
