### ISSUE TITLE
Show backlinks when interacting with markdown preview

### ISSUE THREAD

**Issue by michael-guimet** [svsool/vscode-memo#99]
**Use case**

I tend to use the markdown preview to navigate through my notes and find what I'm looking for. However I have no way of going back to the previous note as the backlinks are missing in preview. I have to open the file to edit (double click) and then go to the backlinks and that completely breaks the navigation flow.

**Current behaviour:**

The "Explorer: Backlinks" panel only shows backlinks when the user is editing a file but is lost (empty) when focus switches to the markdown preview.

**Suggestion**

Show the Backlinks in "Explorer: Backlinks" for a file in the markdown preview when in focus.

**Comment by svsool** [comment]
As of today it's not possible to know which preview (webview) belongs to which text editor and thus it's not possible for backlinks panel to know where to obtain links from. Markdown preview (webview) is controlled by built-in markdown [extension](https://github.com/microsoft/vscode/tree/master/extensions/markdown-language-features/preview-src) via private EventEmitter. 

Workaround is to switch the focus to the text editor for showing backlinks. Double click on preview should open relevant text editor automatically.

The answer on this problem from VS Code team is [here](https://github.com/Microsoft/vscode/issues/49915#issuecomment-389258763). 

I hope this helps.
